name: plan

on:
  workflow_call:
    # inputs:
    #   username:
    #     required: true
    #     type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Plan
        run: Running terraform plan