name: Terraform Plan

on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true

env:
  TF_INPUT: false
  RESOURCE_GROUP: 'rg-terraform'
  STORAGE_ACCOUNT: 'stterraformjr'
  CONTAINER_NAME: 'tfstate'

permissions:
  issues: write
  pull-requests: write
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    env: 
      environment: ${{ github.event.inputs.environment }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Download saved plan from artifacts  
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: tfplan
      - run: zip -r tfplan.zip tfplan/

      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Log in to Azure
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
          STORAGE_ACCOUNT: ${{ env.STORAGE_ACCOUNT }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          # environment: ${{ inputs.environment }}
          environment: ${{ github.event.inputs.environment }}
        run: |
          terraform init \
            -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
            -backend-config="container_name=$CONTAINER_NAME" \
            -backend-config="resource_group_name=$RESOURCE_GROUP" \
            -backend-config="key=$environment/terraform.tfstate"

      # # Download saved plan from artifacts  
      # - name: Download Terraform Plan
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: tfplan
      #     path: tfplan
      # - run: zip -r tfplan.zip tfplan/

      # Run a terraform apply
      - name: Terraform Apply
        id: apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          ls -lah
          terraform apply \
            -auto-approve \
            tfplan