name: MyTestPipeline

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  plan:
    uses: jrampin/github-actions/.github/workflows/templates/plan.yml@main
    # with:
    #   username: Houssem
    # secrets:
    #   token: ${{ secrets.TOKEN }}

  apply:
    uses: jrampin/github-actions/.github/workflows/templates/apply.yml@main
    #   username: Dellai
    # secrets:
    #   token: ${{ secrets.TOKEN }}