name: github-actions

on:
  push:
    branches:
      - '*'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Specifies the GitHub deployment environment.'
        required: false
        type: choice
        default: dev
        options:
          - dev
          - prod

# env:
#   # TF_LOG: INFO
#   TF_INPUT: false
#   RESOURCE_GROUP: 'rg-terraform'
#   STORAGE_ACCOUNT: 'stterraformjr'
#   CONTAINER_NAME: 'tfstate'

permissions:
  issues: write
  pull-requests: write
  contents: read
  id-token: write

jobs:
  terraform-plan:
    uses: ./.github/workflows/plan.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  terraform-apply:
    uses: ./.github/workflows/apply.yml
    needs: terraform-plan
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}