name: My Starter Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specifies the GitHub deployment environment.'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - prod

# env:
#   # TF_LOG: INFO
#   TF_INPUT: false
#   RESOURCE_GROUP: 'rg-terraform'
#   STORAGE_ACCOUNT: 'stterraformjr'
#   CONTAINER_NAME: 'tfstate'

# permissions:
#   issues: write
#   pull-requests: write
#   contents: read
#   id-token: write

jobs:
  terraform-plan:
    uses: ./.github/workflows/plan.yml
