name: github-actions

on:
  push:
    branches:
      - '*'

  # This is used to enable a workflow to be triggered manually.
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specifies the GitHub deployment environment.'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - prod     
  pull_request:     

# env:
#   # TF_LOG: INFO
#   TF_INPUT: false
#   RESOURCE_GROUP: 'rg-terraform'
#   STORAGE_ACCOUNT: 'stterraformjr'
#   CONTAINER_NAME: 'tfstate'

permissions:
  issues: write
  pull-requests: write
  contents: read
  id-token: write

jobs:
  terraform-plan:
    uses: ./.github/workflows/plan.yml

    if: github.event_name != 'workflow_dispatch'

    with:
      environment: 'dev'
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  terraform-apply:
    uses: ./.github/workflows/apply.yml

    # if: github.ref == 'refs/heads/main'
    if: github.event_name == 'workflow_dispatch'
    
    needs: terraform-plan
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}