name: MyTestPipeline

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  plan:
    uses: ./templates/plan.yml
    # with:
    #   username: Houssem
    # secrets:
    #   token: ${{ secrets.TOKEN }}

  apply:
    uses: ./templates/apply.yml
    #   username: Dellai
    # secrets:
    #   token: ${{ secrets.TOKEN }}