name: github-actions

on:
  # This is used to enable a workflow to be triggered manually.
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specifies the GitHub deployment environment.'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - prod                

permissions:
  issues: write
  pull-requests: write
  contents: read
  id-token: write

jobs:
  terraform-plan:
    uses: ./.github/workflows/plan.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  terraform-apply:
    uses: ./.github/workflows/apply.yml   
    needs: terraform-plan
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}