name: MyTestPipeline

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  plan:
    uses: ./.github/actions/plan.yml
    # with:
    #   username: Houssem
    # secrets:
    #   token: ${{ secrets.TOKEN }}

  apply:
    uses: ./.github/actions/apply.yml
    #   username: Dellai
    # secrets:
    #   token: ${{ secrets.TOKEN }}