name: Terraform Workflow

on:
  push:
    branches: [ main ]
    # paths:
    # - '04-workload/*'
  pull_request:
    branches: [ main ]
    # paths:
    # - '04-workload/*'
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Which Environment to deploy?'
    #     required: true
    #     default: 'prod'

# env:
#   ENVIRONMENT: ${{ github.event.inputs.environment }}
#   SERVICE_CONNECTION_NAME: 'sp-terraform-wb-all-aue'
#   SCOPE: '04-workload'

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Plan
      uses: ./.github/actions/plan
      # with:
      #   env: ${{ env.ENVIRONMENT }}
      #   ServiceConnectionName: ${{ env.SERVICE_CONNECTION_NAME }}
      #   Scope: ${{ env.SCOPE }}

  terraform_apply:
    needs: terraform_plan
    # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Apply
      uses: ./.github/actions/apply
      # with:
      #   env: ${{ env.ENVIRONMENT }}
      #   ServiceConnectionName: ${{ env.SERVICE_CONNECTION_NAME }}
      #   Scope: ${{ env.SCOPE }}